### ISSUE TITLE
Cannot install npm packages after installing Git for Windows 

### ISSUE THREAD

**Issue by pieceofchum** [git/git-scm.com#1277]
After installation of Git for Windows I can no longer install npm packages I get the following error. This is unfortunately going to make me fail my final project at college as I have not time to fix before submission.

2674 verbose stack Error: exited with error code: 128
2674 verbose stack     at ChildProcess.onexit (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
2674 verbose stack     at emitTwo (events.js:126:13)
2674 verbose stack     at ChildProcess.emit (events.js:214:7)
2674 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2675 verbose cwd C:\Users\draym\udemy-eth\test
2676 verbose Windows_NT 10.0.17134
2677 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2678 verbose node v8.9.4
2679 verbose npm  v5.6.0
2680 error Error while executing:
2680 error C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
2680 error
2680 error fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )
2680 error
2680 error exited with error code: 128
2681 verbose exit [ 1, true ]

**Comment by pieceofchum** [comment]
I was able to fix this by doing the following:

git config --global url."https://".insteadOf git://
